/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable quotes */
/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable semi */
/* eslint-disable react/react-in-jsx-scope */
/* eslint-disable prettier/prettier */
import React, { useEffect, useContext, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { createFilter } from 'react-search-input';
import { useRouter } from 'next/router'
import Articles from '../../../UI/modules/Articles';
import Header from '../../../UI/components/organisms/Header';
import { ArticlesContext } from '../../../context/Articles';
import { ServiceHighlights } from '../../../services/articles';
import { countLetter } from '../../../utils/functions'
//import Image from 'next/image';

const Home: NextPage = () => {
  const { articles, setArticles } = useContext(ArticlesContext);
  const router = useRouter();
  const { search } = router.query;
  const [filterPreviewSearchValue, setFilterPreviewSearchValue] = useState('');
  const [filtered, setFiltered] = useState([]);
  const KEYS_TO_FILTERS = ['title'];

  const getNameSearch = (value: string | any) => {
    if (value == '') {
      void ServiceHighlights(setArticles, () => { });
    }
    setFilterPreviewSearchValue(value);
  };

  useEffect(() => {
    setFiltered(articles.filter(createFilter(filterPreviewSearchValue, KEYS_TO_FILTERS)));
  }, [filterPreviewSearchValue]);

  useEffect(() => {
    setArticles(filtered);
  }, [filtered]);

  useEffect(() => {
    if (search != undefined && search && search != '') {
      // @ts-ignore
      let searchGet: string = search;
      const count = countLetter(searchGet, '-');
      for (let i = 0; i <= count; i++) {
        searchGet = searchGet.replace("-", " ");
      }
      console.log(searchGet);
      getNameSearch(searchGet);
    }
  }, [articles, search]);

  return (
    <div>
      <Head>
        <title>Space Flight News search: {search}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main
        style={{
          padding: '16px',
          paddingBottom: '32px',
          paddingLeft: '32px',
          paddingRight: '32px',
        }}>
        <hr style={{ marginBottom: '32px' }} />
        <Articles />
      </main>
    </div>
  );
};

export default Home;
